// Generated by CoffeeScript 1.6.1
(function() {
  var app, connect, http;

  connect = require('connect');

  http = require('http');

  app = connect();

  app.use(connect["static"](__dirname));

  app.use("./css", connect["static"]("./css"));

  app.use(connect["static"]("" + __dirname + "./js"));

  http.createServer(app).listen(8080);


  console.log("listening...");

}).call(this);
